# Generated by Django 4.2 on 2023-04-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('conversation_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(blank=True)),
                ('direction', models.CharField(blank=True, choices=[('outgoing', 'outgoing'), ('incoming', 'incoming')], max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_api.chat')),
            ],
        ),
    ]
